version: '3.8'
services:
  cache:
    image: redis:latest
    command: redis-server --requirepass pass123
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: easystorage
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080